namespace SupportIQ.Domain.Entities;

/// <summary>
/// A single normalized tag attached to a <see cref="SupportTicket"/>, generated by AI analysis.
/// </summary>
public class TicketTag
{
    public Guid Id { get; private set; }
    public Guid TicketId { get; private set; }
    public string Value { get; private set; } = default!;

    private TicketTag()
    {
    }

    internal static TicketTag Create(Guid ticketId, string value)
    {
        return new TicketTag
        {
            Id = Guid.NewGuid(),
            TicketId = ticketId,
            Value = value.Trim().ToLowerInvariant()
        };
    }
}
